### ISSUE TITLE
Bootloader logo

### ISSUE THREAD

**Issue by caspermeijn** [lupyuen/pinetime-updater#1]
This is a great project. Flashing the bootloader and InifiniTime is really easy, but I miss the bootloader logo flasher.
After using the updater I get a garbage screen when booting the PineTime. I assume this is because of the missing bootloader logo.

**Comment by hrmckay** [comment]
You can fix this by flashing the watch with pinetime-graphics.bin at address 0x0 before you flash the bootloader and the application.  You can find pinetime-graphics.bin at https://github.com/JF002/Pinetime/releases/download/0.7.1/pinetime-graphics.bin

Hugh

**Comment by caspermeijn** [comment]
Thanks for your reaction, Hugh. I already knew this was possible by flashing such a firmware. I haven't done that yet, because I have to figure how the flashing tools work. I think this would be a great addition to pinetime-updater, so that it is easy for everybody :-)
