### ISSUE TITLE
Error of compilation i guess

### ISSUE THREAD

**Issue by KNG6** [lupyuen/pinetime-updater#11]
![image](https://user-images.githubusercontent.com/27773153/147711966-64549a1b-1347-41e4-a0c9-6ad8906edd88.png)
I'm on raspberry pi
do you have an idea ?

**Comment by lupyuen** [comment]
Try editing src/flash/nor/jtagspi.c, line 262 and change it to:

uint32_t status = 0;

I haven't seen this error before.

**Comment by KNG6** [comment]
![image](https://user-images.githubusercontent.com/27773153/147755652-a7259ecc-cb63-401a-9be3-01e7fdf515b0.png)

**Comment by lupyuen** [comment]
Sorry I'm not using Pi any more, I can't check on this. Could you ask the folks in PineTime Chatroom on Matrix? Thanks

**Comment by KNG6** [comment]
I will, thanks

**Comment by anbcodes** [comment]
For anyone else with the same problem, the solution that worked for me (suggested on [matrix](https://matrix.to/#/!AAFOIMUTWDhXfArnWq:matrix.org/$gU7KoWpb0L1dnBRs9mnCGAzg7pIcOLcnWZKCbSjTzI4?via=matrix.org&via=kde.org&via=one.ems.host)) was to downgrade gcc from 11 to 9

**Comment by lupyuen** [comment]
Ah great thanks!

**Comment by anbcodes** [comment]
There's actually a [pull request](https://github.com/lupyuen/openocd-spi/pull/5) on your other repository for fixing it to work with GCC 10, which appears to be the current default on the Raspberry PI OS. (I had been using GCC 11, as I was using ubuntu on the raspberry pi)

**Comment by lupyuen** [comment]
Yep I just merged it, sorry I missed that :-)
