### ISSUE TITLE
Targets for URL or File Upload

### ISSUE THREAD

**Issue by CCranney** [lupyuen/pinetime-updater#15]
Hi, I'm trying to flash a customized InfiniTime to my PineTime dev kit watch. I was able to flash the latest firmware (option 2), but when I try to download from URL/file the watch is perpetually loading the starting screen. I tried to use the InfiniTime github repository, but had the same error. I am thinking I am typing the wrong path, but am not sure what the right path should be. Would you know where I'm going wrong?

Steps to replicate:
1. Choose "Download from URL"
<img width="567" alt="Screen Shot 2022-10-21 at 2 18 15 PM" src="https://user-images.githubusercontent.com/11773171/197281993-feaa5a8b-a899-4d93-aee2-dbd14744fef8.png">

2. Enter the InfiniTime github repository URL:
https://github.com/InfiniTimeOrg/InfiniTime
<img width="567" alt="Screen Shot 2022-10-21 at 2 22 31 PM" src="https://user-images.githubusercontent.com/11773171/197282366-5128a01e-5ab6-4909-b987-7d5f8905bec0.png">

**Comment by CCranney** [comment]
Sorry, I realized I need to do a few more build steps ([here](https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/buildAndProgram.md)). I may reopen this once I do so if I'm still running into problems. Thank you!

**Comment by lupyuen** [comment]
Yep no problem :-)
