### ISSUE TITLE
What's wrong now?

### ISSUE THREAD

**Issue by jotasprout** [lupyuen/pinetime-updater#2]
I can't figure out what's wrong now at this step. I don't see "done" and what I do get doesn't completely match your logs. 

![20200927_010334](https://user-images.githubusercontent.com/12866150/94374102-fb5bd400-00d7-11eb-9f39-11fae0e8abcc.png)
![20200927_010348](https://user-images.githubusercontent.com/12866150/94374103-fe56c480-00d7-11eb-9490-70e1196c4fbb.png)
![20200927_010359](https://user-images.githubusercontent.com/12866150/94374104-ff87f180-00d7-11eb-8efd-8c88fc904226.png)
![20200927_010423](https://user-images.githubusercontent.com/12866150/94374105-00208800-00d8-11eb-8382-e678e12d7ad8.png)
![20200927_153756](https://user-images.githubusercontent.com/12866150/94374111-09115980-00d8-11eb-94d3-3717163bfb1d.jpg)

**Comment by bajansen** [comment]
The script will always attempt to program through the GPIO pins when run on a Raspberry Pi, regardless of whether an ST-Link adapter is connected. You can override this behaviour by changing the comparison below in `run.sh` to `False`.
 https://github.com/lupyuen/pinetime-updater/blob/8cf00b63164323519ade5bcced70192f6d8a5347/run.sh#L26

**Comment by jotasprout** [comment]
If I make this change to my fork and all goes well, would it be a good Pull Request? Is this a change that should be in the master?
