### ISSUE TITLE
Updates to bootloader and firmware

### ISSUE THREAD

**Issue by TechnologyClassroom** [lupyuen/pinetime-updater#7]
Here are links to the latest bootloader and firmware:

Bootloader: https://github.com/JF002/pinetime-mcuboot-bootloader/releases/download/1.0.0/bootloader.bin

Application Firmware: https://github.com/JF002/InfiniTime/releases/download/1.0.0-RC4/pinetime-mcuboot-app-image-1.0.0.bin

I could make a pull request if you would like.

A more permanent solution over hardcoded values would be to check for the most recent stable release and set that for the url value.  This would be easier for Infinitime than it would be for the bootloader.

**Comment by lupyuen** [comment]
Yes could you please create a PR thanks!
